### ISSUE TITLE
Suggestions from call 11-17

### ISSUE THREAD

**Issue by bruce-usab** [Myndex/SAPC-APCA#10]
- [x] Maybe replace <q>AuxTextgadby</q> with <q>Sample</q> or user choice?
- [x] Please file bug w/ Google wrt Chrome rendering of Jost font.
- [x] How much work would it be for people to pick there own fonts for testing?  Of the 11 you provide samples, I have only used one (Helvetica Neu), and I would not use that one a web site.

**Comment by Myndex** [comment]
Hi Bruce @bruce-usab ... Perhaps **"SampleATgdb"** I'll work on that... the example texts I tend to use like **"&IcyATOMsizedgap"** or **"AuxTextgadby"** are chosen because they have an assortment of glyphs that show you most of what you need to know about a font design: easy to measure cap height and x height, descenders and ascenders, and design class ("ag" being two critical glyphs for classification).

I'll work on the bug report — I'm still investigating the depths of this problem.

As for picking own fonts: very easy for anyone coding it for their own use, and probably not too hard for adding it as a feature. The reason for the fonts that are set as samples is that they all have all weights available. Most fonts don't, so I'd need to create a way to show samples only in the weights available for a font, and that's a bit more work. Will add it as a feature request.

**Comment by Myndex** [comment]
Closing this only because there is going to be a new repo(s) for all Myndex created _TOOLS_ and this repo is for discussion and issues with the underlying math, models, and algorithms. Third party developers are taking the bull by the horns and incorporating APCA all over now....
