### ISSUE TITLE
Conformance levels unclear

### ISSUE THREAD

**Issue by tkeenoy** [Myndex/SAPC-APCA#3]
Not sure if this is the right place to report: on the SAPC tool beta, there is a section for Conformance Levels (color coded). It's unclear how (if at all) to apply these levels. Do they correspond in any way to AA/AAA ratings in the old standards?
<img width="567" alt="Screen Shot 2020-10-08 at 4 32 00 PM" src="https://user-images.githubusercontent.com/58079898/95523654-0b9b6b00-0984-11eb-9c6a-f0365113dc95.png">

**Comment by Myndex** [comment]
Hi @tkeenoy 

Thanks for asking. These have no relationship whatsoever to the existing WCAG 2.x standards.

Conformance and scoring is very much under development for Silver/WCAG 3, and we are working through it all.

Essentially there are five levels, including 0 (fail) with level four being the best outcome. In the scoring model, the scores for different aspects of a site get aggregated and averaged to determine overall site score.

The "initial" example for Visual Contrast is subject to change, but to simplify things it is based on the lowest value on a page.:

- **Rating 4**
    - All reading text meets or exceeds the values on the APCA lookup table 
- **Rating 3**
    - The lowest APCA value is 1-4% below the values on the APCA lookup table
- **Rating 2**
    - The lowest APCA value is 5-9% below the values on the APCA lookup table
- **Rating 1**
    - The lowest APCA value is 10-15% below the values on the APCA lookup table
- **Rating 0**
    - Any failures on the APCA lookup table or the lowest APCA value is more than 15% below the values on the APCA lookup table

At the moment, the [SAPC/APCA tool ](https://www.myndex.com/SAPC/)may not indicate this exactly, as this is a fairly recent development.

### APCA Compared to WCAG 2

The SAPC Algorithm (APCA) and WCAG 2.x only have parity in a very narrow band, with #AAA in the perceptual middle. I.e. where the background is equidistant above #AAA and the font equidistant below #AAA. And the background must be brighter than the text as WCAG 2.x does not handle revered contrast correctly.

Those things in mind, WCAG 4.5:1 is about APCA 80%. 3:1 is ~60%, and 7:1 is ~100%. Here's a chart:

![WCAG 2 to SAPC APCA](https://user-images.githubusercontent.com/42009457/95632404-65f70300-0a3a-11eb-8178-2324bcdc02da.png)


And one other thing on the lookup table: it is based on Helvetica Neue. So for example there's a Google font called Jost that is much thinner in comparison as rendered on some browsers. So for fonts that don't have the equivalent perceptual contrast of Helvetica, you need to offset the values to compensate.

Please let me know if you have further questions.

Andy

**Comment by tkeenoy** [comment]
This is great info, thanks Andy. My team is looking at how to use the new guidelines to inform best practices, and it's exciting seeing them develop.

I'm not clear on the meanings of the center pivot colors in the table you posted here - do you have any expanded docs up about that? Or are you able to elaborate?

**Comment by Myndex** [comment]
> I'm not clear on the meanings of the center pivot colors in the table you posted here - do you have any expanded docs up about that? Or are you able to elaborate?

Hi @tkeenoy 

I have a lot more information posted on the Wiki at:
https://www.w3.org/WAI/GL/task-forces/silver/wiki/Visual_Contrast_of_Text_Subgroup

## _"Engineered on Purpose"_ 😁
The SAPC math is engineered to put the key values at easy to remember levels: 40% 60% 80% 100% 120% etc. And I specifically wanted **60%, 80%, 100%** to line up at some point with WCAG 2.x's **3:1, 4.5:1,** and **7:1**, if for no other reason than to be able to say that _"80% is about like the old 4.5:1"_. As it happens, the old 2.x math method really starts to breakdown when both colors are below `#AAA`or if the text is above `#AAA` among other things. This became a convenient color to have as a line up point so that there would be a point where SAPC and WCAG values matched and results were "similar". 

It's a very narrow band, with the background color equally far above `#AAA` as the text color is below (hence `#AAA` _pivots_ in the middle). Outside of this band, WCAG and SAPC do not line up — nor would you expect them to. SAPC/APCA is a perceptually based prediction method and the old 2.x is not. 

So in the above chart, the BG and text colors and the pivot point are only listed to indicate the _one place_ where 80% APCA equals 4.5:1 WCAG 2.x etc.

## The 80% Trick
This only works for the 80% level, and the results are not exact, but still useful:
- If you divide 80 by the first digit of font weight, you'll get a close approximation of the minimum font size in px for the 80% level.  
    - Example: A 200 weight font. 80 / 2 = 40px (actual minimum is 36px)
    - Example: A 500 weight font. 80 / 5 = 16px (actual minimum is in fact 16px)

- Alternately if you divide 80 by the font size, you'll get a close approximation of the first digit of the minimum weight for that font size at 80%.
    - Example: A 24px font. 80 / 24 = 3.3 (actual minimum weight is 300)
    - Example: An 18px font. 80 / 18 = 4.4 (actual minimum weight is 400)
    - Example: A 14px font. 80 / 14 = 5.7 (actual minimum weight is 600)

These may change over the coming months as this is all beta including the lookup table. The results pivot around 16px 500wt, over estimating for lower weights/bigger sizes and underestimating for higher weights — but keep in mind that 12px is the minimum font size _anyway_, and 12px should only be used for things like copyright or photo by-line, and never for readable text. The "real minimum" is 16px, and 18px preferred for readable text (text intended to be read).

**Comment by Myndex** [comment]
## UPDATE:

On review: subtracting 10% form 120% is not at all the same as subtracting 10% from 40%. Currently working on a scoring model that (like the rest) relates strongly to perception. Stay tuned, and remember this is all beta at the moment.

If you want a "sneak peak" of some things we are working on but are very much ALPHA, you can take a look at the discussions page on our Wiki. I just posted a set of new charts for multi level scoring:  https://www.w3.org/WAI/GL/task-forces/silver/wiki/Talk:Visual_Contrast_of_Text_Subgroup#Integrating_Lookup_Tables_into_a_Scoring_Model

I love to hear comments, but do keep in mind this is rough and early developmental stuff.

## APCA vs WCAG 2.x (simplified)

As I mentioned, you can't really compare the two methods for a variety of reasons. But if we realy need to state how they compare, I'd put it like this:

- APCA **80** is similar to WCAG **4.5:1** for a site using light or white backgrounds with dark text. 
- However, APCA provides more granular guidance on the critical properties of font weight and size, which are inseparable from luminance contrast as part of the overall contrast perception and readability factors.

**Comment by joshuakraemer** [comment]
> * APCA **80** is similar to WCAG **4.5:1** for a site using light or white backgrounds with dark text.

Is this still correct? The calculator page https://www.myndex.com/APCA/ and the wiki page https://www.w3.org/WAI/GL/task-forces/silver/wiki/Visual_Contrast_of_Text_Subgroup compare an APCA value of 60% to WGAG 4.5:1.

**Comment by Myndex** [comment]
Hi @joshuakraemer 

Egads... yes much has changed since this thread was written, I should close it probably to prevent this confusion...

See issue #11 for some clarity on this...


Andy
