### ISSUE TITLE
First impression suggestions

### ISSUE THREAD

**Issue by bruce-usab** [Myndex/SAPC-APCA#6]
Looking really great!  My first impression critiques from Silver call 11/3:
- [x] Swap foreground text color and background color at top of page.
* It took me more than a minute (!) to spot where the selected text color / background color were being demonstrated (since it is in the middle).
  - Order at top is background / sample / text color.  Since we (in the west) read left-to-right, this would ideally be sample / text color / background color.  But that would really mix up the layout.
  - In any case, I strongly recommend swapping text color with background color (in the top section).
- [x] Replace <q>N/A</q> as used for when Score 1 (or even Score 2) is automatic.
* <q>not applicable</q> is not an accurate label when any font size will achieved Score 1 (or 2).
  - I don't have a great suggestion, but even <q>OK</q> or <q>np</q> (for no problem) would be better.

**Comment by bruce-usab** [comment]
Very popular tools like [Webaim Contrast Checker](https://webaim.org/resources/contrastchecker/) and [TPG CCA](https://www.paciellogroup.com/color-contrast-checker/) put foreground color on the left, and background color on the right.

**Comment by Myndex** [comment]
Hi Bruce @bruce-usab 

Yea, I noticed that about the WebAim checker and have been wondering if I should swap the input fields. Will do.

And I hear you regarding N/A -- that was a _"well I gotta put something in"_  while in the midst of coding. "OK" is a pretty good idea. I was also thinking of "see level above" ... there is a part of the conformance model I didn't mention because it's not functioning yet, which is that I'm going to have some adjustment lookups per level that define things like text use (i.e. only for copyright, not for bodytext, etc) and trying to figure out how to indicate...

**Comment by Myndex** [comment]
Addressed, went with "OK" for now

**Comment by bruce-usab** [comment]
Thanks!

Also I love the `<td class="copyOnly">©§™</td>` change!
